import json

food = {
  "food": [
    {
      "value": "Hus",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 1584,
      "kcal": 278,
      "protein": 14,
      "carbs": 0.5,
      "fat": 20,
      "key": 0
    },
    {
      "value": "Ka\u010dica",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 1227,
      "kcal": 292,
      "protein": 16,
      "carbs": 0.5,
      "fat": 23,
      "key": 1
    },
    {
      "value": "Kuracie prsia",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 470,
      "kcal": 116,
      "protein": 24,
      "carbs": 0,
      "fat": 3,
      "key": 2
    },
    {
      "value": "Kuracie stehno",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 489,
      "kcal": 116,
      "protein": 20,
      "carbs": 0,
      "fat": 5,
      "key": 3
    },
    {
      "value": "Kuracie vypr\u00e1\u017e.",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 1202,
      "kcal": 286,
      "protein": 22,
      "carbs": 1.5,
      "fat": 8,
      "key": 4
    },
    {
      "value": "Kuracie dusen\u00e9",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 631,
      "kcal": 150,
      "protein": 25,
      "carbs": 0,
      "fat": 5,
      "key": 5
    },
    {
      "value": "Mor\u010dacie prsia",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 471,
      "kcal": 112,
      "protein": 25,
      "carbs": 0,
      "fat": 1,
      "key": 6
    },
    {
      "value": "Mor\u010dacie stehno",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 492,
      "kcal": 117,
      "protein": 21,
      "carbs": 0,
      "fat": 2.5,
      "key": 7
    },
    {
      "value": "P\u00e1rky hydinov\u00e9",
      "category": "Hydina",
      "unit": "Gramy",
      "base": 100,
      "kj": 1017,
      "kcal": 242,
      "protein": 12,
      "carbs": 1,
      "fat": 21,
      "key": 8
    },
    {
      "value": "Brav\u010dov\u00fd b\u00f4\u010dik",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1532,
      "kcal": 365,
      "protein": 11,
      "carbs": 0,
      "fat": 28,
      "key": 9
    },
    {
      "value": "Brav\u010dov\u00e9 koleno",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1339,
      "kcal": 320,
      "protein": 17,
      "carbs": 0,
      "fat": 27,
      "key": 10
    },
    {
      "value": "Brav\u010dov\u00e1 krkovi\u010dka",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1289,
      "kcal": 308,
      "protein": 23,
      "carbs": 0,
      "fat": 23,
      "key": 11
    },
    {
      "value": "Brav\u010dov\u00e9 pliecko",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1001,
      "kcal": 239,
      "protein": 18,
      "carbs": 0,
      "fat": 18,
      "key": 12
    },
    {
      "value": "Brav\u010dov\u00e9 stehno",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 921,
      "kcal": 390,
      "protein": 16,
      "carbs": 0,
      "fat": 16,
      "key": 13
    },
    {
      "value": "Brav\u010dov\u00e9 p\u00e1rky",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1467,
      "kcal": 350,
      "protein": 25,
      "carbs": 2,
      "fat": 25,
      "key": 14
    },
    {
      "value": "Brav\u010dov\u00e1 slanina",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 342,
      "kcal": 823,
      "protein": 84,
      "carbs": 0,
      "fat": 84,
      "key": 15
    },
    {
      "value": "Brav\u010dov\u00e1 \u0161unka",
      "category": "Brav\u010dov\u00e9 m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1089,
      "kcal": 260,
      "protein": 9,
      "carbs": 2,
      "fat": 9,
      "key": 16
    },
    {
      "value": "Hov\u00e4dzie stehno",
      "category": "Hov\u00e4dzie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 766,
      "kcal": 183,
      "protein": 21,
      "carbs": 0,
      "fat": 9,
      "key": 17
    },
    {
      "value": "Hov\u00e4dzie pliecko",
      "category": "Hov\u00e4dzie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 783,
      "kcal": 187,
      "protein": 19,
      "carbs": 0,
      "fat": 11,
      "key": 18
    },
    {
      "value": "Hov\u00e4dzia ro\u0161tenka",
      "category": "Hov\u00e4dzie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 909,
      "kcal": 217,
      "protein": 21,
      "carbs": 0,
      "fat": 13,
      "key": 19
    },
    {
      "value": "Hov\u00e4dzia svie\u010dkov\u00e1",
      "category": "Hov\u00e4dzie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 687,
      "kcal": 164,
      "protein": 22,
      "carbs": 0,
      "fat": 8,
      "key": 20
    },
    {
      "value": "Kapor",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 520,
      "kcal": 124,
      "protein": 17,
      "carbs": 0,
      "fat": 6,
      "key": 21
    },
    {
      "value": "Krab",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 220,
      "kcal": 53,
      "protein": 14,
      "carbs": 0,
      "fat": 2,
      "key": 22
    },
    {
      "value": "Krevety",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1120,
      "kcal": 267,
      "protein": 24,
      "carbs": 2,
      "fat": 12,
      "key": 23
    },
    {
      "value": "Losos",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 680,
      "kcal": 162,
      "protein": 18,
      "carbs": 0,
      "fat": 15,
      "key": 24
    },
    {
      "value": "Makrela",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 855,
      "kcal": 204,
      "protein": 18,
      "carbs": 0,
      "fat": 14,
      "key": 25
    },
    {
      "value": "Pstruh",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 710,
      "kcal": 169,
      "protein": 20,
      "carbs": 0,
      "fat": 10,
      "key": 26
    },
    {
      "value": "Sardinky v oleji",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 1130,
      "kcal": 270,
      "protein": 17,
      "carbs": 0,
      "fat": 15,
      "key": 27
    },
    {
      "value": "Sardinky v om\u00e1\u010dke",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 740,
      "kcal": 188,
      "protein": 17,
      "carbs": 2,
      "fat": 11,
      "key": 28
    },
    {
      "value": "Sle\u010f",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 924,
      "kcal": 220,
      "protein": 17,
      "carbs": 0,
      "fat": 15,
      "key": 29
    },
    {
      "value": "Treska alja\u0161sk\u00e1",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 490,
      "kcal": 117,
      "protein": 14,
      "carbs": 0,
      "fat": 6,
      "key": 30
    },
    {
      "value": "Treska \u0161al\u00e1t",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 920,
      "kcal": 219,
      "protein": 11,
      "carbs": 7,
      "fat": 14,
      "key": 31
    },
    {
      "value": "Tuniak",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 620,
      "kcal": 148,
      "protein": 21,
      "carbs": 0,
      "fat": 5,
      "key": 32
    },
    {
      "value": "Tuniak v oleji",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 940,
      "kcal": 224,
      "protein": 18,
      "carbs": 0,
      "fat": 11,
      "key": 33
    },
    {
      "value": "Tuniak vo vlastnej \u0161\u0165ave",
      "category": "Rybacie m\u00e4so",
      "unit": "Gramy",
      "base": 100,
      "kj": 630,
      "kcal": 150,
      "protein": 19,
      "carbs": 0,
      "fat": 4,
      "key": 34
    },
    {
      "value": "Sal\u00e1ma Vyso\u010dina",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 1923,
      "kcal": 459,
      "protein": 19.3,
      "carbs": 0,
      "fat": 42.6,
      "key": 35
    },
    {
      "value": "Sal\u00e1ma Debrec\u00ednska",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 878,
      "kcal": 209,
      "protein": 15.4,
      "carbs": 2.2,
      "fat": 14.8,
      "key": 36
    },
    {
      "value": "Sal\u00e1ma Mor\u010dacia",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 693,
      "kcal": 169,
      "protein": 17.6,
      "carbs": 0,
      "fat": 14.9,
      "key": 37
    },
    {
      "value": "Sal\u00e1ma kabanos",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 858,
      "kcal": 209,
      "protein": 14.8,
      "carbs": 2.1,
      "fat": 14.1,
      "key": 38
    },
    {
      "value": "Sal\u00e1ma Hydinov\u00e1",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 1528,
      "kcal": 373,
      "protein": 26.3,
      "carbs": 0.2,
      "fat": 28.7,
      "key": 39
    },
    {
      "value": "\u0160unka kuracia",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 652,
      "kcal": 156,
      "protein": 18,
      "carbs": 2,
      "fat": 3.5,
      "key": 40
    },
    {
      "value": "\u0160unka mor\u010dacia",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 541,
      "kcal": 129,
      "protein": 20,
      "carbs": 2,
      "fat": 3,
      "key": 41
    },
    {
      "value": "\u0160unka Hydinov\u00e1",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 928,
      "kcal": 226,
      "protein": 26.6,
      "carbs": 0.1,
      "fat": 12.6,
      "key": 42
    },
    {
      "value": "\u0160unka dusen\u00e1",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 655,
      "kcal": 156,
      "protein": 16.2,
      "carbs": 1.7,
      "fat": 9.7,
      "key": 43
    },
    {
      "value": "Klob\u00e1sa Ostravsk\u00e1",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 1299,
      "kcal": 317,
      "protein": 17.9,
      "carbs": 1.7,
      "fat": 24.9,
      "key": 44
    },
    {
      "value": "Klob\u00e1sa Moravsk\u00e1",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 875,
      "kcal": 213,
      "protein": 15.7,
      "carbs": 1.4,
      "fat": 24.8,
      "key": 45
    },
    {
      "value": "Kabanos",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 1247,
      "kcal": 297,
      "protein": 12.7,
      "carbs": 1.7,
      "fat": 26.4,
      "key": 46
    },
    {
      "value": "Slanina",
      "category": "Sal\u00e1my, \u0160unky, \u00dadeniny",
      "unit": "Gramy",
      "base": 100,
      "kj": 3406,
      "kcal": 811,
      "protein": 2.9,
      "carbs": 0.2,
      "fat": 89.3,
      "key": 47
    },
    {
      "value": "Bakla\u017e\u00e1n",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 105,
      "kcal": 25.6,
      "protein": 1,
      "carbs": 5.1,
      "fat": 0,
      "key": 48
    },
    {
      "value": "Brokolica",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 135,
      "kcal": 32.9,
      "protein": 4.5,
      "carbs": 3.9,
      "fat": 0.7,
      "key": 49
    },
    {
      "value": "Cesnak",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 670,
      "kcal": 163.4,
      "protein": 6.4,
      "carbs": 32,
      "fat": 0.6,
      "key": 50
    },
    {
      "value": "Cibu\u013ea",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 170,
      "kcal": 41.4,
      "protein": 1.1,
      "carbs": 8.5,
      "fat": 0.1,
      "key": 51
    },
    {
      "value": "Cibu\u013ea \u010derven\u00e1",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 161,
      "kcal": 39.2,
      "protein": 1.3,
      "carbs": 8.1,
      "fat": 0.1,
      "key": 52
    },
    {
      "value": "Cukina",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 75,
      "kcal": 18.3,
      "protein": 1.9,
      "carbs": 1.8,
      "fat": 0.2,
      "key": 53
    },
    {
      "value": "\u010cerven\u00e1 repa",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 182,
      "kcal": 44.4,
      "protein": 1.7,
      "carbs": 10,
      "fat": 0.1,
      "key": 54
    },
    {
      "value": "\u010c\u00ednska kapusta",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 52,
      "kcal": 12.7,
      "protein": 1,
      "carbs": 1.8,
      "fat": 0,
      "key": 55
    },
    {
      "value": "Fefer\u00f3nky",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 74,
      "kcal": 18,
      "protein": 0.6,
      "carbs": 3.5,
      "fat": 0.1,
      "key": 56
    },
    {
      "value": "Hl\u00e1vkov\u00e1 kapusta",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 160,
      "kcal": 39,
      "protein": 2.6,
      "carbs": 5.5,
      "fat": 0.3,
      "key": 57
    },
    {
      "value": "Hr\u00e1\u0161ok",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 365,
      "kcal": 87,
      "protein": 7,
      "carbs": 13,
      "fat": 0,
      "key": 58
    },
    {
      "value": "Chren",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 95,
      "kcal": 23.1,
      "protein": 2,
      "carbs": 4.6,
      "fat": 0.1,
      "key": 59
    },
    {
      "value": "Kaler\u00e1b",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 109,
      "kcal": 26,
      "protein": 2,
      "carbs": 4,
      "fat": 0,
      "key": 60
    },
    {
      "value": "Karfiol",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 120,
      "kcal": 29,
      "protein": 2,
      "carbs": 4,
      "fat": 0,
      "key": 61
    },
    {
      "value": "K\u00e1pia",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 158,
      "kcal": 38.5,
      "protein": 1,
      "carbs": 6,
      "fat": 0.2,
      "key": 62
    },
    {
      "value": "Mrkva",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 175,
      "kcal": 42.7,
      "protein": 1,
      "carbs": 7.2,
      "fat": 0.1,
      "key": 63
    },
    {
      "value": "Olivy",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 610,
      "kcal": 148.7,
      "protein": 0.8,
      "carbs": 3.9,
      "fat": 10,
      "key": 64
    },
    {
      "value": "Paprika biela, zelen\u00e1",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 52,
      "kcal": 12.7,
      "protein": 0.7,
      "carbs": 3.1,
      "fat": 0,
      "key": 65
    },
    {
      "value": "Paprika \u017elt\u00e1",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 115,
      "kcal": 28,
      "protein": 1,
      "carbs": 6,
      "fat": 0.9,
      "key": 66
    },
    {
      "value": "Paradajky",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 93,
      "kcal": 22.7,
      "protein": 1,
      "carbs": 4.1,
      "fat": 0,
      "key": 67
    },
    {
      "value": "Patiz\u00f3n",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 222,
      "kcal": 54.1,
      "protein": 2.5,
      "carbs": 9.8,
      "fat": 0.2,
      "key": 68
    },
    {
      "value": "Petr\u017elen",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 230,
      "kcal": 56.1,
      "protein": 1,
      "carbs": 4.3,
      "fat": 0.2,
      "key": 69
    },
    {
      "value": "Po\u013en\u00e1 uhorka",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 67,
      "kcal": 16.3,
      "protein": 0.6,
      "carbs": 2.5,
      "fat": 0.1,
      "key": 70
    },
    {
      "value": "P\u00f3r",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 160,
      "kcal": 38,
      "protein": 2,
      "carbs": 6,
      "fat": 0,
      "key": 71
    },
    {
      "value": "Re\u010fkovka",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 110,
      "kcal": 26.8,
      "protein": 1.5,
      "carbs": 7,
      "fat": 0.1,
      "key": 72
    },
    {
      "value": "\u0160al\u00e1tov\u00e1 uhorka",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 66,
      "kcal": 16.1,
      "protein": 0.6,
      "carbs": 2.4,
      "fat": 0.1,
      "key": 73
    },
    {
      "value": "\u0160pen\u00e1t",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 109,
      "kcal": 26,
      "protein": 3,
      "carbs": 3,
      "fat": 0,
      "key": 74
    },
    {
      "value": "\u0160parg\u013ea",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 80,
      "kcal": 19,
      "protein": 2,
      "carbs": 3,
      "fat": 0,
      "key": 75
    },
    {
      "value": "Zeler",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 207,
      "kcal": 50.5,
      "protein": 2.2,
      "carbs": 11,
      "fat": 0,
      "key": 76
    },
    {
      "value": "Zemiaky",
      "category": "Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 328,
      "kcal": 80,
      "protein": 2.8,
      "carbs": 17.3,
      "fat": 0.3,
      "key": 77
    },
    {
      "value": "Biela kapusta",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 87,
      "kcal": 21.2,
      "protein": 1.4,
      "carbs": 1,
      "fat": 0.2,
      "key": 78
    },
    {
      "value": "\u010calam\u00e1da",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 130,
      "kcal": 31.7,
      "protein": 1.1,
      "carbs": 10,
      "fat": 0.2,
      "key": 79
    },
    {
      "value": "\u010cerven\u00e1 repa",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 135,
      "kcal": 32.9,
      "protein": 0.7,
      "carbs": 7,
      "fat": 0,
      "key": 80
    },
    {
      "value": "Hr\u00e1\u0161ok",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 299,
      "kcal": 72.9,
      "protein": 5.2,
      "carbs": 8.8,
      "fat": 0.5,
      "key": 81
    },
    {
      "value": "Kukurica",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 505,
      "kcal": 123.1,
      "protein": 3,
      "carbs": 22,
      "fat": 1,
      "key": 82
    },
    {
      "value": "Kysl\u00e1 kapusta",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 70,
      "kcal": 17,
      "protein": 0,
      "carbs": 2,
      "fat": 0,
      "key": 83
    },
    {
      "value": "Le\u010do",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 120,
      "kcal": 29.2,
      "protein": 0,
      "carbs": 6.2,
      "fat": 0.1,
      "key": 84
    },
    {
      "value": "Mrkva",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 111,
      "kcal": 27,
      "protein": 0.5,
      "carbs": 5,
      "fat": 0,
      "key": 85
    },
    {
      "value": "Paradajkov\u00fd pretlak",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 124,
      "kcal": 30.2,
      "protein": 1.1,
      "carbs": 3.9,
      "fat": 0.1,
      "key": 86
    },
    {
      "value": "Uhorky",
      "category": "Zav\u00e1ran\u00e1 Zelenina",
      "unit": "Gramy",
      "base": 100,
      "kj": 120,
      "kcal": 29.2,
      "protein": 1.3,
      "carbs": 4.9,
      "fat": 0.1,
      "key": 87
    },
    {
      "value": "Anan\u00e1s",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 192,
      "kcal": 47,
      "protein": 0.4,
      "carbs": 9.8,
      "fat": 0,
      "key": 88
    },
    {
      "value": "Avok\u00e1do",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 328,
      "kcal": 80,
      "protein": 1.1,
      "carbs": 0.5,
      "fat": 1.6,
      "key": 89
    },
    {
      "value": "Ban\u00e1n",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 206.6,
      "kcal": 49.3,
      "protein": 0.6,
      "carbs": 11.6,
      "fat": 0,
      "key": 90
    },
    {
      "value": "Brosky\u0148a",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 196.8,
      "kcal": 48,
      "protein": 0.8,
      "carbs": 8,
      "fat": 0.07,
      "key": 91
    },
    {
      "value": "Citr\u00f3n",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 123,
      "kcal": 30,
      "protein": 0.5,
      "carbs": 2.5,
      "fat": 0,
      "key": 92
    },
    {
      "value": "\u010cere\u0161ne",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 270,
      "kcal": 64,
      "protein": 1,
      "carbs": 15,
      "fat": 0,
      "key": 93
    },
    {
      "value": "Figy",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 319.8,
      "kcal": 78,
      "protein": 1.4,
      "carbs": 16.3,
      "fat": 0.3,
      "key": 94
    },
    {
      "value": "Gran\u00e1tov\u00e9 jablko",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 237.8,
      "kcal": 58,
      "protein": 1.4,
      "carbs": 10.7,
      "fat": 0.1,
      "key": 95
    },
    {
      "value": "Grep",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 160,
      "kcal": 39,
      "protein": 2,
      "carbs": 20,
      "fat": 0.15,
      "key": 96
    },
    {
      "value": "Hrozno biele",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 291.1,
      "kcal": 71,
      "protein": 1.6,
      "carbs": 15,
      "fat": 0.2,
      "key": 97
    },
    {
      "value": "Hrozno modr\u00e9",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 300,
      "kcal": 72,
      "protein": 1,
      "carbs": 17,
      "fat": 0,
      "key": 98
    },
    {
      "value": "Hru\u0161ka",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 270.6,
      "kcal": 66,
      "protein": 0.5,
      "carbs": 14,
      "fat": 0.3,
      "key": 99
    },
    {
      "value": "Jablko",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 254.2,
      "kcal": 62,
      "protein": 0.4,
      "carbs": 14,
      "fat": 0,
      "key": 100
    },
    {
      "value": "Jahody",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 150,
      "kcal": 36,
      "protein": 1,
      "carbs": 8,
      "fat": 0,
      "key": 101
    },
    {
      "value": "Kivi",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 205,
      "kcal": 50,
      "protein": 1,
      "carbs": 9,
      "fat": 0,
      "key": 102
    },
    {
      "value": "Maliny",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 229.6,
      "kcal": 56,
      "protein": 1.2,
      "carbs": 12.5,
      "fat": 0,
      "key": 103
    },
    {
      "value": "Mandarinka",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 176.3,
      "kcal": 43,
      "protein": 0.7,
      "carbs": 10.6,
      "fat": 0.2,
      "key": 104
    },
    {
      "value": "Mango",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 254.2,
      "kcal": 62,
      "protein": 0.6,
      "carbs": 16,
      "fat": 0.39,
      "key": 105
    },
    {
      "value": "Marhule",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 237.8,
      "kcal": 58,
      "protein": 1.5,
      "carbs": 11,
      "fat": 0.3,
      "key": 106
    },
    {
      "value": "Mel\u00f3n \u010derven\u00fd",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 150,
      "kcal": 36.5,
      "protein": 0.4,
      "carbs": 14,
      "fat": 0,
      "key": 107
    },
    {
      "value": "Mel\u00f3n \u017elt\u00fd",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 150,
      "kcal": 36.5,
      "protein": 0.5,
      "carbs": 9,
      "fat": 0.1,
      "key": 108
    },
    {
      "value": "Nektarinky",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 143.5,
      "kcal": 35,
      "protein": 1.1,
      "carbs": 7.8,
      "fat": 0.1,
      "key": 109
    },
    {
      "value": "Pap\u00e1ja",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 176.3,
      "kcal": 43,
      "protein": 2.1,
      "carbs": 10,
      "fat": 0,
      "key": 110
    },
    {
      "value": "Pomaran\u010d",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 226,
      "kcal": 55.2,
      "protein": 1.3,
      "carbs": 12,
      "fat": 0,
      "key": 111
    },
    {
      "value": "Pomelo",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 168.1,
      "kcal": 41,
      "protein": 0.9,
      "carbs": 10,
      "fat": 0,
      "key": 112
    },
    {
      "value": "Slivky",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 220,
      "kcal": 53.6,
      "protein": 0.8,
      "carbs": 12,
      "fat": 0.2,
      "key": 113
    },
    {
      "value": "Vi\u0161ne",
      "category": "Ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 221.4,
      "kcal": 54,
      "protein": 1,
      "carbs": 12,
      "fat": 0.6,
      "key": 114
    },
    {
      "value": "Anan\u00e1s",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1200,
      "kcal": 292.6,
      "protein": 3.6,
      "carbs": 55,
      "fat": 1.2,
      "key": 115
    },
    {
      "value": "Ban\u00e1n",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1350,
      "kcal": 329.2,
      "protein": 4.5,
      "carbs": 74,
      "fat": 0.7,
      "key": 116
    },
    {
      "value": "Brusnice",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1020,
      "kcal": 248.7,
      "protein": 1,
      "carbs": 61,
      "fat": 0.6,
      "key": 117
    },
    {
      "value": "\u010eatle",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1160,
      "kcal": 282.9,
      "protein": 3.1,
      "carbs": 76,
      "fat": 0.3,
      "key": 118
    },
    {
      "value": "Figy",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1030,
      "kcal": 251.2,
      "protein": 3.5,
      "carbs": 53,
      "fat": 1.5,
      "key": 119
    },
    {
      "value": "Hrozienka",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1280,
      "kcal": 312.1,
      "protein": 1,
      "carbs": 69,
      "fat": 0,
      "key": 120
    },
    {
      "value": "Jablk\u00e1",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1250,
      "kcal": 304.8,
      "protein": 1.4,
      "carbs": 69.5,
      "fat": 1.3,
      "key": 121
    },
    {
      "value": "Jahody",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1030,
      "kcal": 251.2,
      "protein": 1.7,
      "carbs": 54,
      "fat": 0,
      "key": 122
    },
    {
      "value": "Marhule",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1000,
      "kcal": 243.9,
      "protein": 6,
      "carbs": 51,
      "fat": 1,
      "key": 123
    },
    {
      "value": "Slivky",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1130,
      "kcal": 275.6,
      "protein": 3,
      "carbs": 72,
      "fat": 0.7,
      "key": 124
    },
    {
      "value": "Vi\u0161ne",
      "category": "Su\u0161en\u00e9 ovocie",
      "unit": "Gramy",
      "base": 100,
      "kj": 1250,
      "kcal": 304.8,
      "protein": 4.5,
      "carbs": 68,
      "fat": 1,
      "key": 125
    },
    {
      "value": "Mlieko nízkotučné",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 160,
      "kcal": 38,
      "protein": 3,
      "carbs": 5,
      "fat": 0.5
    },
    {
      "value": "Mlieko polotučné",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 194,
      "kcal": 46,
      "protein": 3.2,
      "carbs": 4.6,
      "fat": 1.5
    },
    {
      "value": "Mlieko plnotučné",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 267,
      "kcal": 64,
      "protein": 3.3,
      "carbs": 4.7,
      "fat": 3.5
    },
    {
      "value": "Acidofilné mlieko",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 272,
      "kcal": 65,
      "protein": 3.2,
      "carbs": 2.8,
      "fat": 3.6
    },
    {
      "value": "Kozie mlieko",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 254,
      "kcal": 60,
      "protein": 3.5,
      "carbs": 4.2,
      "fat": 3.9
    },
    {
      "value": "Ovčie mlieko",
      "category": "Mlieko",
      "unit": "ML",
      "base": 100,
      "kj": 452,
      "kcal": 108,
      "protein": 5.7,
      "carbs": 5.4,
      "fat": 7.3
    },
    {
      "value": "Jogurt biely",
      "category": "Jogurty",
      "unit": "Gramy",
      "base": 100,
      "kj": 402,
      "kcal": 96,
      "protein": 4,
      "carbs": 13,
      "fat": 2.5
    },
    {
      "value": "Jogurt ovocný",
      "category": "Jogurty",
      "unit": "Gramy",
      "base": 100,
      "kj": 600,
      "kcal": 143,
      "protein": 4,
      "carbs": 21,
      "fat": 5
    },
    {
      "value": "Jogurt čokoládový",
      "category": "Jogurty",
      "unit": "Gramy",
      "base": 100,
      "kj": 490,
      "kcal": 117,
      "protein": 3.3,
      "carbs": 21.6,
      "fat": 3.8
    },
    {
      "value": "Jogurt nízkotučný",
      "category": "Jogurty",
      "unit": "Gramy",
      "base": 100,
      "kj": 238,
      "kcal": 56,
      "protein": 6.3,
      "carbs": 6.9,
      "fat": 0.1
    },
    {
      "value": "Syr Eidam 20%",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 967,
      "kcal": 231,
      "protein": 32,
      "carbs": 2.9,
      "fat": 11.1
    },
    {
      "value": "Syr Eidam 30%",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1108,
      "kcal": 264,
      "protein": 29,
      "carbs": 1.7,
      "fat": 14.2
    },
    {
      "value": "Syr Eidam 40%",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1293,
      "kcal": 308,
      "protein": 26,
      "carbs": 1.2,
      "fat": 17.6
    },
    {
      "value": "Syr Eidam 45%",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1700,
      "kcal": 406,
      "protein": 27,
      "carbs": 3,
      "fat": 25
    },
    {
      "value": "Bryndza",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1137,
      "kcal": 271,
      "protein": 23.4,
      "carbs": 1.9,
      "fat": 22.4
    },
    {
      "value": "Hermelín",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1118,
      "kcal": 266,
      "protein": 18.9,
      "carbs": 1.1,
      "fat": 19.7
    },
    {
      "value": "Syr tavený",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1237,
      "kcal": 295,
      "protein": 14.7,
      "carbs": 1.3,
      "fat": 24.9
    },
    {
      "value": "Syr ovčí",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1412,
      "kcal": 336,
      "protein": 21.8,
      "carbs": 0.3,
      "fat": 27.8
    },
    {
      "value": "Parmezán",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 1695,
      "kcal": 404,
      "protein": 38.3,
      "carbs": 0.1,
      "fat": 31.4
    },
    {
      "value": "Syrokrém",
      "category": "Syry",
      "unit": "Gramy",
      "base": 100,
      "kj": 676,
      "kcal": 162,
      "protein": 13.5,
      "carbs": 4.5,
      "fat": 10
    },
    {
      "value": "Tvaroh Plnotučný",
      "category": "Tvaroh",
      "unit": "Gramy",
      "base": 100,
      "kj": 674,
      "kcal": 161,
      "protein": 21,
      "carbs": 4.2,
      "fat": 3.2
    },
    {
      "value": "Tvaroh polotučný",
      "category": "Tvaroh",
      "unit": "Gramy",
      "base": 100,
      "kj": 460,
      "kcal": 109,
      "protein": 19.2,
      "carbs": 3.9,
      "fat": 2.1
    },
    {
      "value": "Tvaroh ochutený",
      "category": "Tvaroh",
      "unit": "Gramy",
      "base": 100,
      "kj": 590,
      "kcal": 141,
      "protein": 14.7,
      "carbs": 16.2,
      "fat": 2.3
    },
    {
      "value": "Smotanová nátierka",
      "category": "Maslo, nátierky",
      "unit": "Gramy",
      "base": 100,
      "kj": 1310,
      "kcal": 317,
      "protein": 2.7,
      "carbs": 6.4,
      "fat": 31
    },
    {
      "value": "Maslo",
      "category": "Maslo, nátierky",
      "unit": "Gramy",
      "base": 100,
      "kj": 3072,
      "kcal": 747,
      "protein": 0.8,
      "carbs": 0.7,
      "fat": 82.2
    },
    {
      "value": "Smotana na varenie 10%",
      "category": "Smotana",
      "unit": "Gramy",
      "base": 100,
      "kj": 498,
      "kcal": 119,
      "protein": 3.2,
      "carbs": 4.3,
      "fat": 10
    },
    {
      "value": "Smotana na šľahanie 33%",
      "category": "Smotana",
      "unit": "Gramy",
      "base": 100,
      "kj": 300,
      "kcal": 1257,
      "protein": 2.2,
      "carbs": 3.3,
      "fat": 32.8
    },

    {
      "value": "Bageta",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 290,
      "kj": 1215,
      "fat": 0.6,
      "carbs": 59,
      "protein": 8
    },
    {
      "value": "Chlieb biely",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 233,
      "kj": 980,
      "fat": 1.5,
      "carbs": 48,
      "protein": 8
    },
    {
      "value": "Chlieb celozrnný",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 220,
      "kj": 920,
      "fat": 2,
      "carbs": 49,
      "protein": 8
    },
    {
      "value": "Chlieb celoz.ražný",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 183,
      "kj": 766,
      "fat": 1,
      "carbs": 36,
      "protein": 6
    },
    {
      "value": "Chlieb kmínový",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 247,
      "kj": 1340,
      "fat": 1.8,
      "carbs": 43,
      "protein": 7
    },
    {
      "value": "Chlieb rascový",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 235,
      "kj": 990,
      "fat": 1,
      "carbs": 50,
      "protein": 8
    },
    {
      "value": "Chlieb ražný",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 201,
      "kj": 850,
      "fat": 1.5,
      "carbs": 50,
      "protein": 7
    },
    {
      "value": "Chlieb toustový",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 269,
      "kj": 1127,
      "fat": 3.7,
      "carbs": 51,
      "protein": 8
    },
    {
      "value": "Chlieb zemiakový",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 233,
      "kj": 980,
      "fat": 1,
      "carbs": 51,
      "protein": 8
    },
    {
      "value": "Knackebrot",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 282,
      "kj": 1180,
      "fat": 2.2,
      "carbs": 66,
      "protein": 12
    },
    {
      "value": "Rožok biely",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 286,
      "kj": 1200,
      "fat": 3,
      "carbs": 60,
      "protein": 10
    },
    {
      "value": "Rožok grahamový",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 290,
      "kj": 1220,
      "fat": 3,
      "carbs": 59,
      "protein": 10
    },
    {
      "value": "Strúhanka",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 380,
      "kj": 1560,
      "fat": 3.5,
      "carbs": 79,
      "protein": 10
    },
    {
      "value": "Žemľa biela",
      "category": "Pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 290,
      "kj": 1200,
      "fat": 3,
      "carbs": 60,
      "protein": 10
    },
    {
      "value": "Bábovka",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 400,
      "kj": 1640,
      "tuky": 24,
      "cukry": 45,
      "bielk": 4
    },
    {
      "value": "Buchty",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 410,
      "kj": 1690,
      "tuky": 17,
      "cukry": 54,
      "bielk": 9
    },
    {
      "value": "Croissant",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 430,
      "kj": 1780,
      "tuky": 28,
      "cukry": 40,
      "bielk": 4
    },
    {
      "value": "Kaiserka",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 487,
      "kj": 1202,
      "tuky": 2,
      "cukry": 52,
      "bielk": 7
    },
    {
      "value": "Koláč kysnutý",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 390,
      "kj": 1600,
      "tuky": 16,
      "cukry": 55,
      "bielk": 5
    },
    {
      "value": "Koláč makový",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 367,
      "kj": 1537,
      "tuky": 15,
      "cukry": 54,
      "bielk": 7
    },
    {
      "value": "Koláč tvarohový",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 323,
      "kj": 1353,
      "tuky": 11,
      "cukry": 52,
      "bielk": 11
    },
    {
      "value": "Piškóty",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 370,
      "kj": 1510,
      "tuky": 2,
      "cukry": 77,
      "bielk": 8
    },
    {
      "value": "Šiška",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 327,
      "kj": 1558,
      "tuky": 17,
      "cukry": 69,
      "bielk": 6
    },
    {
      "value": "Vianočka",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 360,
      "kj": 1470,
      "tuky": 9,
      "cukry": 61,
      "bielk": 8
    },
    {
      "value": "Závin",
      "category": "Sladké pečivo",
      "unit": "Gramy",
      "base": 100,
      "kcal": 400,
      "kj": 1630,
      "tuky": 16,
      "cukry": 56,
      "bielk": 9
    },

    {
      "value": "Citrónová šťava",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 47,
      "kj": 194,
      "tuky": 0.0,
      "cukry": 11.1,
      "bielk": 0.0
    },
    {
      "value": "Coca cola",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 41,
      "kj": 169,
      "tuky": 0.0,
      "cukry": 10.6,
      "bielk": 0.0
    },
    {
      "value": "Coca Cola zero",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 0.09,
      "kj": 0.03,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Čaj nesladený",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 1,
      "kj": 4,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Fanta",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 35,
      "kj": 158,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Hanácka kyselka",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 16,
      "kj": 65,
      "tuky": 0,
      "cukry": 3.2,
      "bielk": 0
    },
    {
      "value": "Káva",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 12.19,
      "kj": 51,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Kofola Original",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 33,
      "kj": 140,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Mattoni pomaranč",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 21,
      "kj": 85,
      "tuky": 0,
      "cukry": 0,
      "bielk": 0
    },
    {
      "value": "Pepsi",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 48,
      "kj": 197,
      "tuky": 0,
      "cukry": 11.5,
      "bielk": 0
    },
    {
      "value": "Pivo nealko",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 19,
      "kj": 80,
      "tuky": 0.0,
      "cukry": 2.1,
      "bielk": 0.17
    },
    {
      "value": "Red Bull",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 18,
      "kj": 74.8,
      "tuky": 0.0,
      "cukry": 5.3,
      "bielk": 0.0
    },
    {
      "value": "Sirup ovocný",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 278,
      "kj": 1167,
      "tuky": 0.3,
      "cukry": 78.9,
      "bielk": 0.4
    },
    {
      "value": "Sprite",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 38,
      "kj": 159,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Tonic",
      "category": "Nealko",
      "unit": "ML",
      "base": 100,
      "kcal": 54,
      "kj": 225,
      "tuky": 0.0,
      "cukry": 0.0,
      "bielk": 0.0
    },
    {
      "value": "Amaretto",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 271,
      "kj": 1135,
      "fat": 15,
      "carbs": 31,
      "protein": 28
    },
    {
      "value": "Becherovka",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 278,
      "kj": 1164,
      "fat": 0,
      "carbs": 8,
      "protein": 0
    },
    {
      "value": "Burčiak",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 102,
      "kj": 427,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Gin 45%",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 254,
      "kj": 1042,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Mojito",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 69,
      "kj": 289,
      "fat": 0,
      "carbs": 4,
      "protein": 0
    },
    {
      "value": "Pivo svetlé 10°",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 32,
      "kj": 134,
      "fat": 3.4,
      "carbs": 3,
      "protein": 0.2
    },
    {
      "value": "Pivo svetlé 12°",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 34,
      "kj": 144,
      "fat": 3.6,
      "carbs": 6,
      "protein": 0.3
    },
    {
      "value": "Pivo tmavé 10°",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 51,
      "kj": 215,
      "fat": 3.8,
      "carbs": 3,
      "protein": 0.4
    },
    {
      "value": "Radler",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 113,
      "kj": 27,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Rum",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 223,
      "kj": 936,
      "fat": 4,
      "carbs": 77.4,
      "protein": 6
    },
    {
      "value": "Sekt",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 83,
      "kj": 347,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Slivovica 40°",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 226,
      "kj": 949,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Vaječný koňak",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 333,
      "kj": 1403,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Vermut",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 134,
      "kj": 561,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Víno biele",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 55,
      "kj": 231,
      "fat": 0,
      "carbs": 0.1,
      "protein": 0.1
    },
    {
      "value": "Víno červené",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 67,
      "kj": 281,
      "fat": 0,
      "carbs": 0.2,
      "protein": 0.2
    },
    {
      "value": "Vodka",
      "category": "Alkohol",
      "unit": "ML",
      "base": 100,
      "kcal": 227,
      "kj": 953,
      "fat": 0,
      "carbs": 0,
      "protein": 0
    },
    {
      "value": "Čokoláda horká",
      "category": "Sladkosti",
      "unit": "Gramy",
      "base": 100,
      "kcal": 528,
      "kj": 2217.6,
      "fat": 33,
      "carbs": 60,
      "protein": 10
    },
    {
      "value": "Čokoláda mliečna",
      "category": "Sladkosti",
      "unit": "Gramy",
      "base": 100,
      "kcal": 532,
      "kj": 2234.4,
      "fat": 35,
      "carbs": 64,
      "protein": 5.5
    },
    {
      "value": "Čokoláda na varenie",
      "category": "Sladkosti",
      "unit": "Gramy",
      "base": 100,
      "kcal": 530,
      "kj": 2226,
      "fat": 28,
      "carbs": 65,
      "protein": 6.5
    },
    {
      "value": "Nutella",
      "category": "Sladkosti",
      "unit": "Gramy",
      "base": 100,
      "kcal": 550,
      "kj": 2310,
      "fat": 32,
      "carbs": 60,
      "protein": 4
    },
    {
      "value": "Piškóty",
      "category": "Sladkosti",
      "unit": "Gramy",
      "base": 100,
      "kcal": 380,
      "kj": 1596,
      "fat": 14,
      "carbs": 72,
      "protein": 0.5
    },
    {
      "value": "vajce",
      "category": "Vajcia",
      "unit": "Kus",
      "base": 1,
      "kcal": 84,
      "kj": 350,
      "protein": 7,
      "fat": 6,
      "carbs": 0
    },
    {
      "value": "bielok",
      "category": "Vajcia",
      "unit": "Kus",
      "base": 1,
      "kcal": 17,
      "kj": 70,
      "protein": 3,
      "fat": 0,
      "carbs": 0
    },
    {
      "value": "žĺtok",
      "category": "Vajcia",
      "unit": "Kus",
      "base": 1,
      "kcal": 69,
      "kj": 290,
      "protein": 3,
      "fat": 6,
      "carbs": 0
    },
    {
      "value": "ovsené vločiek",
      "category": "Obilniny",
      "unit": "Gramy",
      "base": 100,
      "kcal": 334,
      "kj": 1400,
      "protein": 10,
      "fat": 10,
      "carbs": 70
    }
  ]
}




for i, item in enumerate(food["food"]):
    # print(item, i)
    item["key"] = i
    # print(item, i)
    

json_object = json.dumps(food, indent=4)

with open("sample.json", "w") as of:
    of.write(json_object)